name: 🐞 Bug report
description: Report a bug or an issue.
title: 'bug: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        # microG RE bug report

        Before creating a new bug report, please keep the following in mind:

        - **Do not submit a duplicate bug report**: Search for existing bug reports [here](https://github.com/MorpheApp/MicroG-RE/issues?q=is%3Aissue).
  - type: textarea
    attributes:
      label: Bug description
      description: |
        - Add steps to reproduce the bug if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
    validations:
        required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed bug reports and this is not a duplicate.
          required: true
        - label: All requested information has been provided properly.
          required: true
