name: 💬 Discussion
description: Open a new discussion.
title: 'discussion: '
labels: ['discussion']
body:
  - type: markdown
    attributes:
      value: |
        # microG RE Discussion

        Before creating a new discussion, please keep the following in mind:

        - **Do not create duplicate discussions that already exist as other discussions or as bug/feature requests**: Search for existing similar issues here [here](https://github.com/MorpheApp/MicroG-RE/issues?q=is%3Aissue).
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed bug reports and this is not a duplicate.
          required: true
